-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
        exclude: ^\.activate\.sh$
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: name-tests-test
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-added-large-files
        language_version: python3.6
        exclude: ^\.activate\.sh$
    -   id: check-byte-order-marker
        language_version: python3.6
    -   id: fix-encoding-pragma
        args: [--remove]
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: v0.3.4
    hooks:
    -   id: reorder-python-imports
        args: [
            --remove-import, 'from __future__ import absolute_import',
            --remove-import, 'from __future__ import print_function',
            --remove-import, 'from __future__ import unicode_literals',
        ]
        language_version: python3.6
-   repo: git@git.yelpcorp.com:packages/swagger-tools
    sha: v3.2.3
    hooks:
    -   id: validate-swagger
        args: [--service, 'clusterman']
        files: api_docs/swagger.json
        language_version: python3.6
-   repo: git@git.yelpcorp.com:mirrors/asottile/pyupgrade
    sha: v1.1.1
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
        language_version: python3.6
