version: "2"

services:
  moto-ec2:
    build: ./moto/
    ports:
      - 5000
    command: 'ec2'
  moto-s3:
    build: ./moto/
    ports:
      - 5000
    command: 's3'
  moto-dynamodb:
    build: ./moto/
    ports:
      - 5000
    command: 'dynamodb2'

networks:
  default:
    external:
      name: kind
